 
runtime: python27
api_version: 1
version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/[project-name]/index.html
  upload:  dist/[project-name]/index.html
- url: /
  script: dist/[project-name]
 
